# Generated by Django 6.1 on 2026-09-14 22:07

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='account',
            name='accounts_ac_user_id_31d6a5_idx',
        ),
    ]
