[project]
name = "backend"
version = "0.1.0"
description = "Shared backend for Card Case"
requires-python = ">=3.13"
dependencies = [
    "django>=6.1,<7.0",
    "django-allauth[headless]>=65.19.1",
    "django-environ>=0.14.0,<0.15.0",
    "psycopg[binary]>=3.3.4,<4.0.0",
]

[tool.ruff]
extend-exclude = ["*/migrations/*"]

[dependency-groups]
dev = [
    "django-stubs>=6.1.0,<6.2.0",
    "pre-commit>=4.6.2,<5.0.0",
    "ruff>=0.16.3,<0.16.4",
]
