name: Web CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

defaults:
  run:
    working-directory: web

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-web
      - run: pnpm run build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-web
      - run: pnpm run format:check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-web
      - run: pnpm run lint
